name: CI Pipeline
on:
  push:
    # branches-ignore:
    #   - main

jobs:
  test:
    name: Install dependencies and run unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Run unit tests
        run: npm run test

  container-test:
    name: Run unit tests inside a Docker container in dev mode
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker image in Dev Mode
        run: docker build -t markmaksi/testing-series -f Dockerfile.dev .
      - name: Run tests in the container
        run: docker run markmaksi/testing-series npm run test

  aws-build:
    name: Run unit tests inside a Docker container in dev mode
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t markmaksi/testing-series -f Dockerfile .
      - run: docker run -e CI=true markmaksi/testing-series npm run test

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: frontend
          environment_name: Frontend-env
          existing_bucket_name: elasticbeanstalk-eu-central-1-580978446433
          region: eu-central-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip