name: CI Pipeline
on:
  push:
    # branches-ignore:
    #   - main

jobs:
  test:
    name: Run npm test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Run npm test
        run: npm run test

  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker image in Dev Mode
        run: docker build -t markmaksi/testing-series -f Dockerfile.dev .
      - name: Run tests in the container
        run: docker run markmaksi/testing-series npm run test