name: Deploy Next.js App
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t markmaksi/testing-series -f Dockerfile.dev .
      - run: docker run -e CI=true markmaksi/testing-series npm run test

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: next-docker-app
          environment_name: Next-docker-app-env
          region: eu-central-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
